#!/usr/bin/env bun

/**
 * 生成嵌入式翻译模块。
 * 将 lang/ 目录下所有 JSON 文件转为静态 import，
 * 使翻译数据在编译时嵌入二进制，无需运行时读取文件系统。
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

const langDir = path.join(import.meta.dir, "..", "src", "i18n", "lang");
const outFile = path.join(import.meta.dir, "..", "src", "i18n", "embedded-translations.ts");

const files = await fs.readdir(langDir);
const jsonFiles = files.filter(f => f.endsWith(".json")).sort();

let output = "// Auto-generated by scripts/generate-embedded-translations.ts\n";
output += "// Do not edit manually.\n\n";
output += 'import type { TranslationFile } from "./index";\n\n';

for (const file of jsonFiles) {
	const varname = file.replace(/[.-]/g, "_");
	output += `import ${varname} from "./lang/${file}" with { type: "json" };\n`;
}

output += "\nexport const EMBEDDED_TRANSLATIONS: Record<string, TranslationFile> = {\n";
for (const file of jsonFiles) {
	const key = file.replace(/\.json$/, "");
	const varname = file.replace(/[.-]/g, "_");
	output += `  "${key}": ${varname} as TranslationFile,\n`;
}
output += "};\n";

await Bun.write(outFile, output);
process.stdout.write(`Generated embedded-translations.ts (${jsonFiles.length} files)\n`);
