import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { resetSettingsForTest, Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { assertEditableFile, assertEditableFileContent } from "@oh-my-pi/pi-coding-agent/tools/auto-generated-guard";
import { ToolError } from "@oh-my-pi/pi-coding-agent/tools/tool-errors";

let tempDir: string;
/** Session settings with the guard on — the production default. */
let blocking: Settings;
/** Session settings with the guard opted out (SDK/subagent override). */
let permissive: Settings;

beforeAll(async () => {
	// Deliberately left uninitialized for the whole file: the guard must never
	// reach for the global singleton (see "session settings isolation" below).
	resetSettingsForTest();
	tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "auto-gen-guard-"));
	blocking = Settings.isolated();
	permissive = Settings.isolated({ "edit.blockAutoGenerated": false });
});

afterAll(async () => {
	resetSettingsForTest();
	await fs.rm(tempDir, { recursive: true, force: true });
});

describe("assertEditableFileContent", () => {
	it("detects canonical TypeScript generated header", () => {
		const content = "// Code generated by sqlc. DO NOT EDIT.\n\nexport const foo = 1;";
		expect(() => assertEditableFileContent(content, "test.ts", blocking)).toThrow(ToolError);
	});

	it("detects @generated marker", () => {
		const content = "// @generated\n\nexport const foo = 1;";
		expect(() => assertEditableFileContent(content, "test.ts", blocking)).toThrow(ToolError);
	});

	it("detects generated-by marker for Python files", () => {
		const content = "# Generated by buf\n\nvalue = 1";
		expect(() => assertEditableFileContent(content, "test.py", blocking)).toThrow(ToolError);
	});

	it("detects generated-by marker for SQL files", () => {
		const content = "-- generated by sqlc\n\nselect 1;";
		expect(() => assertEditableFileContent(content, "query.sql", blocking)).toThrow(ToolError);
	});

	it("detects generated markers in leading block comments", () => {
		const content = "/*\n * Code generated by mockery. DO NOT EDIT.\n */\nexport const foo = 1;";
		expect(() => assertEditableFileContent(content, "test.ts", blocking)).toThrow(ToolError);
	});

	it("detects kysely-codegen generated header", () => {
		const content =
			"/**\n * This file was generated by kysely-codegen.\n * Please do not edit it manually.\n */\n\nexport interface Database {}";
		expect(() => assertEditableFileContent(content, "db.ts", blocking)).toThrow(ToolError);
	});
});

describe("assertEditableFile", () => {
	it("detects content marker from file prefix", async () => {
		const filePath = path.join(tempDir, "service.ts");
		await Bun.write(filePath, "// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;");
		await expect(assertEditableFile(filePath, filePath, blocking)).rejects.toBeInstanceOf(ToolError);
	});

	it("allows normal files", async () => {
		const filePath = path.join(tempDir, "normal.ts");
		await Bun.write(filePath, "// Regular source file\nexport const foo = 1;");
		await expect(assertEditableFile(filePath, filePath, blocking)).resolves.toBeUndefined();
	});

	it("handles missing files gracefully", async () => {
		const filePath = path.join(tempDir, "does-not-exist.ts");
		await expect(assertEditableFile(filePath, filePath, blocking)).resolves.toBeUndefined();
	});
});

// Regression coverage for #6549: the guard used to read the global `settings`
// proxy, so it threw "Settings not initialized" whenever it ran before
// `Settings.init()` (SDK embedders, subagents, tests) and ignored a session's
// own `edit.blockAutoGenerated` override when it did resolve.
describe("session settings isolation", () => {
	it("honors a session opt-out for content checks", () => {
		expect(() => assertEditableFileContent("// @generated", "gen.ts", permissive)).not.toThrow();
	});

	it("honors a session opt-out for file checks", async () => {
		const filePath = path.join(tempDir, "opt-out.ts");
		await Bun.write(filePath, "// Code generated by sqlc. DO NOT EDIT.");
		await expect(assertEditableFile(filePath, filePath, permissive)).resolves.toBeUndefined();
	});

	it("does not touch the global settings singleton", async () => {
		// The global is uninitialized for this whole file, so a reintroduced
		// global read surfaces here as "Settings not initialized".
		expect(() => assertEditableFileContent("// Regular code", "normal.ts", blocking)).not.toThrow();
		expect(() => assertEditableFileContent("// @generated", "gen.ts", blocking)).toThrow(ToolError);

		const normalFile = path.join(tempDir, "uninit-normal.ts");
		await Bun.write(normalFile, "// Regular source file");
		await expect(assertEditableFile(normalFile, normalFile, blocking)).resolves.toBeUndefined();

		const genFile = path.join(tempDir, "uninit-gen.ts");
		await Bun.write(genFile, "// Code generated by sqlc. DO NOT EDIT.");
		await expect(assertEditableFile(genFile, genFile, blocking)).rejects.toBeInstanceOf(ToolError);
	});
});
