import { loadNative } from "./loader-state.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

const nativeBindings = loadNative();
// --- generated native exports (do not edit) ---
// classes
export const AudioCapture = nativeBindings.AudioCapture;
export const AudioPlayback = nativeBindings.AudioPlayback;
export const DesktopSession = nativeBindings.DesktopSession;
export const LiveWebRtcPeer = nativeBindings.LiveWebRtcPeer;
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const MacOSPowerAssertion = nativeBindings.MacOSPowerAssertion;
export const NativeBrowserPipe = nativeBindings.NativeBrowserPipe;
export const NativeLaunchEnvironment = nativeBindings.NativeLaunchEnvironment;
export const NativeLocalEndpoint = nativeBindings.NativeLocalEndpoint;
export const NativeLocalListener = nativeBindings.NativeLocalListener;
export const NativeOwnedBrowserProcess = nativeBindings.NativeOwnedBrowserProcess;
export const NativeOwnedFile = nativeBindings.NativeOwnedFile;
export const NativeRuntimeBundle = nativeBindings.NativeRuntimeBundle;
export const NativeVerifiedRuntimeLaunch = nativeBindings.NativeVerifiedRuntimeLaunch;
export const PreparedVerifiedRuntimeLaunch = nativeBindings.PreparedVerifiedRuntimeLaunch;
export const NativeOwnedProcess = nativeBindings.NativeOwnedProcess;
export const NativePeerConnection = nativeBindings.NativePeerConnection;
export const NativeProcessIdentity = nativeBindings.NativeProcessIdentity;
export const NativeVerifiedExecutable = nativeBindings.NativeVerifiedExecutable;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;

// functions
export const __ompInstallTokioRuntime = nativeBindings.__ompInstallTokioRuntime;
export const __piNativesV17_2_5 = nativeBindings.__piNativesV17_2_5;
export const astEdit = nativeBindings.astEdit;
export const astGrep = nativeBindings.astGrep;
export const astMatch = nativeBindings.astMatch;
export const blockRangeAt = nativeBindings.blockRangeAt;
export const copyOwnedFilePrivate = nativeBindings.copyOwnedFilePrivate;
export const copyToClipboard = nativeBindings.copyToClipboard;
export const cosineSimilarityPairs = nativeBindings.cosineSimilarityPairs;
export const countTokens = nativeBindings.countTokens;
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance;
export const deviceCheckGenerateToken = nativeBindings.deviceCheckGenerateToken;
export const diffLineRuns = nativeBindings.diffLineRuns;
export const diffLines = nativeBindings.diffLines;
export const diffWords = nativeBindings.diffWords;
export const enclosingBlockBoundaries = nativeBindings.enclosingBlockBoundaries;
export const encodeSixel = nativeBindings.encodeSixel;
export const executeShell = nativeBindings.executeShell;
export const extractSegments = nativeBindings.extractSegments;
export const fuzzyFind = nativeBindings.fuzzyFind;
export const getSupportedLanguages = nativeBindings.getSupportedLanguages;
export const getWorkProfile = nativeBindings.getWorkProfile;
export const glob = nativeBindings.glob;
export const grep = nativeBindings.grep;
export const hasMatch = nativeBindings.hasMatch;
export const highlightCode = nativeBindings.highlightCode;
export const htmlToMarkdown = nativeBindings.htmlToMarkdown;
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache;
export const isoBackend = nativeBindings.isoBackend;
export const isoDiff = nativeBindings.isoDiff;
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError;
export const isoProbe = nativeBindings.isoProbe;
export const isoResolve = nativeBindings.isoResolve;
export const isoStart = nativeBindings.isoStart;
export const isoStop = nativeBindings.isoStop;
export const listWorkspace = nativeBindings.listWorkspace;
export const matchesKey = nativeBindings.matchesKey;
export const matchesKittySequence = nativeBindings.matchesKittySequence;
export const matchesLegacySequence = nativeBindings.matchesLegacySequence;
export const mmrRerankIndices = nativeBindings.mmrRerankIndices;
export const parseKey = nativeBindings.parseKey;
export const parseKittySequence = nativeBindings.parseKittySequence;
export const readImageFromClipboard = nativeBindings.readImageFromClipboard;
export const renderSnapcompactPng = nativeBindings.renderSnapcompactPng;
export const search = nativeBindings.search;
export const setHangulCompatJamoWidthOverride = nativeBindings.setHangulCompatJamoWidthOverride;
export const sliceWithWidth = nativeBindings.sliceWithWidth;
export const snapcompactSupportedChars = nativeBindings.snapcompactSupportedChars;
export const structuredPatchHunks = nativeBindings.structuredPatchHunks;
export const summarizeCode = nativeBindings.summarizeCode;
export const supportsLanguage = nativeBindings.supportsLanguage;
export const truncateToWidth = nativeBindings.truncateToWidth;
export const vectorIndexTopK = nativeBindings.vectorIndexTopK;
export const visibleWidth = nativeBindings.visibleWidth;
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi;
export const acquireOwnedFileLock = nativeBindings.acquireOwnedFileLock;
export const connectInheritedBroker = nativeBindings.connectInheritedBroker;
export const connectLocal = nativeBindings.connectLocal;
export const createLaunchEnvironment = nativeBindings.createLaunchEnvironment;
export const currentProcessIdentity = nativeBindings.currentProcessIdentity;
export const isProcessIdentityLive = nativeBindings.isProcessIdentityLive;
export const launchVerifiedBrowser = nativeBindings.launchVerifiedBrowser;
export const launchVerifiedProcess = nativeBindings.launchVerifiedProcess;
export const matchesOwnedChild = nativeBindings.matchesOwnedChild;
export const matchesProcessIdentity = nativeBindings.matchesProcessIdentity;
export const openOrCreateOwnedDirectory = nativeBindings.openOrCreateOwnedDirectory;
export const openOrCreatePrivateDirectory = nativeBindings.openOrCreatePrivateDirectory;
export const openOwnedChild = nativeBindings.openOwnedChild;
export const openOwnerPrivateFile = nativeBindings.openOwnerPrivateFile;
export const openPrivateDirectory = nativeBindings.openPrivateDirectory;
export const openInheritedBrokerBootstrap = nativeBindings.openInheritedBrokerBootstrap;
export const openInheritedRuntimeKey = nativeBindings.openInheritedRuntimeKey;
export const installRuntimeBundleAtomic = nativeBindings.installRuntimeBundleAtomic;
export const openRuntimeBundle = nativeBindings.openRuntimeBundle;
export const openExecutable = nativeBindings.openExecutable;
export const openVerifiedExecutable = nativeBindings.openVerifiedExecutable;
export const prepareVerifiedRuntimeLaunch = nativeBindings.prepareVerifiedRuntimeLaunch;
export const openVerifiedExecutableMatching = nativeBindings.openVerifiedExecutableMatching;
export const removeOwnedFileAtomic = nativeBindings.removeOwnedFileAtomic;
export const removeOwnedTreeAtomic = nativeBindings.removeOwnedTreeAtomic;
export const replaceOwnedFileAtomic = nativeBindings.replaceOwnedFileAtomic;
export const verifyExecutableVersion = nativeBindings.verifyExecutableVersion;
export const verifyPeerDescendant = nativeBindings.verifyPeerDescendant;
export const verifyRuntimeBundle = nativeBindings.verifyRuntimeBundle;

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
export const NativeBrowserFeatureToggle = {
	DisableBackgroundNetworking: "disable-background-networking",
	DisableComponentUpdate: "disable-component-update",
	DisableDefaultApps: "disable-default-apps",
};
// --- end generated native exports ---
