"""Repository rule generating the hermetic clang-cl + xwin MSVC cc toolchain.

The @msvc_cc repo holds only cheap generated files — wrapper shell scripts and
the cc_toolchain/cc_toolchain_config BUILD — so iterating on flags here never
invalidates the big @llvm_msvc_tools / @xwin_sysroot downloads (their rules
live in llvm.bzl / sysroot.bzl on purpose).

Wrappers derive every path from $0 (execroot-relative sibling repos), so they
work from Bazel actions (cwd = execroot) and from build scripts, where
rules_rust ${pwd}-expands CC/AR to absolute paths and cc-rs/cmake spawn the
tools from other working directories:

    bin/clang-cl         --target=x86_64-pc-windows-msvc, /imsvc CRT+SDK
                         includes, -msse4.1 -msse4.2 (win32-x64 baseline
                         floor), and target-specific x86_64 libraries.
    bin/clang-cl-arm64   --target=aarch64-pc-windows-msvc with the aarch64
                         CRT/SDK libraries and no inherited x86 ISA flags.
    bin/lld-link[-arm64] /libpath for the matching CRT + SDK libraries;
                         rustc uses it via -Clinker for the msvc flavor.
    bin/llvm-lib[-arm64] archiver (lib.exe replacement, cc-rs AR + CMake).
    bin/llvm-rc[-arm64]  resource compiler.
    bin/llvm-mt[-arm64]  manifest tool.
    bin/ml64.exe         x64-only MASM shim → llvm-ml -m64 (also `ml64`);
                         ARM64 assembly actions use clang-cl-arm64 and can
                         never route through the x64 assembler.

The MSVC-flavored feature/action config (dynamic CRT /MD by default — matching
what napi/cc-rs produced under cargo-xwin; /MT only via the standard
static_link_msvcrt feature) comes from rules_cc's own
windows_cc_toolchain_config.bzl, copied into the repo exactly like
@local_config_cc does, so it always matches the resolved rules_cc version.
"""

_CLANG_CL_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. clang-cl driver for {target}
# against the matching @xwin_sysroot MSVC CRT + Windows SDK libraries.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
splat="$execroot/external/{xwin}/splat"
# lld-link (spawned through -fuse-ld for compiler-driver links, e.g. cmake
# try_compile) resolves CRT/SDK import libs via the link.exe-style LIB env.
LIB="$splat/crt/lib/{arch};$splat/sdk/lib/um/{arch};$splat/sdk/lib/ucrt/{arch}"
export LIB
exec "$llvm/bin/clang-cl" \\
  --target={target} \\
  {target_flags} \\
  -fuse-ld=lld-link \\
  -Wno-unused-command-line-argument \\
  "/imsvc$splat/crt/include" \\
  "/imsvc$splat/sdk/include/ucrt" \\
  "/imsvc$splat/sdk/include/um" \\
  "/imsvc$splat/sdk/include/shared" \\
  "/imsvc$splat/sdk/include/winrt" \\
  "/imsvc$splat/sdk/include/cppwinrt" \\
  "$@"
"""

_LLD_LINK_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. lld-link for {target} with
# matching @xwin_sysroot CRT + SDK libpaths.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
splat="$execroot/external/{xwin}/splat"
# rustc addresses lld in generic multi-flavor style ("-flavor link" first);
# the single-flavor lld-link binary would treat "link" as an input file.
if [ "${{1:-}}" = "-flavor" ]; then shift 2; fi
exec "$llvm/bin/lld-link" \\
  "/libpath:$splat/crt/lib/{arch}" \\
  "/libpath:$splat/sdk/lib/um/{arch}" \\
  "/libpath:$splat/sdk/lib/ucrt/{arch}" \\
  "$@"
"""

_PASSTHROUGH_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
exec "$execroot/external/{llvm}/bin/{tool}" "$@"
"""

_ML64_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. MASM shim: cc-rs assembles .asm
# for x64 msvc targets (blake3's blake3_*_x86-64_windows_msvc.asm) by invoking
# `ml64.exe` from PATH on non-windows hosts; llvm-ml is a MASM-compatible
# replacement — same shim cargo-xwin installed. The blake3 crate.annotation in
# MODULE.bazel prepends this bin/ dir to the build script PATH.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
exec "$execroot/external/{llvm}/bin/llvm-ml" -m64 "$@"
"""

_NOP_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/msvc:cc.bzl. Placeholder for tools the MSVC
# toolchain does not have (gcov/nm/objcopy/objdump/strip).
exit 0
"""

# CMake toolchain files for the `cmake` crate (audiopus_sys' bundled opus).
# cmake's vs_link_exe helper insists on rc/mt tools for MSVC-ABI exe links
# (try_compile links a test exe), and CMake's own find_program would only look
# for `rc`/`mt` on PATH. CMAKE_CURRENT_LIST_DIR makes each file self-locating.
# Handed to build scripts via target-suffixed annotations in MODULE.bazel.
_TOOLCHAIN_CMAKE = """\
# Generated by //bazel/toolchains/msvc:cc.bzl — clang-cl + lld-link + xwin
# CRT/SDK cross toolchain for {target}.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR {processor})
set(CMAKE_C_COMPILER "${{CMAKE_CURRENT_LIST_DIR}}/bin/{clang_cl}")
set(CMAKE_CXX_COMPILER "${{CMAKE_CURRENT_LIST_DIR}}/bin/{clang_cl}")
set(CMAKE_LINKER "${{CMAKE_CURRENT_LIST_DIR}}/bin/{lld_link}")
set(CMAKE_RC_COMPILER "${{CMAKE_CURRENT_LIST_DIR}}/bin/{llvm_rc}")
set(CMAKE_MT "${{CMAKE_CURRENT_LIST_DIR}}/bin/{llvm_mt}")
# The xwin splat carries release CRT import libs only (msvcrt.lib, no
# msvcrtd.lib — same as cargo-xwin). try_compile defaults to the Debug
# configuration, whose /MDd would demand the debug CRT; pin try_compile to
# Release and the runtime library to dynamic release /MD for every config.
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
"""

_BUILD = """\
# Generated by //bazel/toolchains/msvc:cc.bzl — hermetic target-specific
# clang-cl + lld-link + xwin CRT/SDK toolchains for x86_64 and aarch64 MSVC.

load("@rules_cc//cc/toolchains:cc_toolchain.bzl", "cc_toolchain")
load(":windows_cc_toolchain_config.bzl", "cc_toolchain_config")

package(default_visibility = ["//visibility:public"])

filegroup(name = "empty")

filegroup(
    name = "wrappers",
    srcs = [
        "bin/clang-cl",
        "bin/lld-link",
        "bin/llvm-lib",
        "bin/llvm-mt",
        "bin/llvm-rc",
        "bin/ml64",
        "bin/ml64.exe",
        "bin/msvc-nop",
        "toolchain.cmake",
    ],
)

filegroup(
    name = "wrappers_arm64",
    srcs = [
        "bin/clang-cl-arm64",
        "bin/lld-link-arm64",
        "bin/llvm-lib-arm64",
        "bin/llvm-mt-arm64",
        "bin/llvm-rc-arm64",
        "bin/msvc-nop-arm64",
        "toolchain-arm64.cmake",
    ],
)

filegroup(
    name = "all_files",
    srcs = [
        ":wrappers",
        "@llvm_msvc_tools//:x86_64-pc-windows-msvc",
        "@xwin_sysroot//:sysroot",
    ],
)

filegroup(
    name = "all_files_arm64",
    srcs = [
        ":wrappers_arm64",
        "@llvm_msvc_tools//:aarch64-pc-windows-msvc",
        "@xwin_sysroot//:sysroot_arm64",
    ],
)

cc_toolchain_config(
    name = "clang_cl_xwin_config",
    abi_libc_version = "local",
    abi_version = "local",
    archiver_flags = ["/MACHINE:X64"],
    compiler = "clang-cl",
    cpu = "x64_windows",
    dbg_mode_debug_flag = "/DEBUG",
    default_link_flags = ["/MACHINE:X64"],
    fastbuild_mode_debug_flag = "/DEBUG",
    host_system_name = "local",
    msvc_cl_path = "bin/clang-cl",
    msvc_env_include = "{env_include}",
    msvc_env_lib = "{env_lib_x64}",
    msvc_env_path = "/usr/bin:/bin",
    msvc_env_tmp = "/tmp",
    msvc_lib_path = "bin/llvm-lib",
    msvc_link_path = "bin/lld-link",
    msvc_ml_path = "bin/ml64.exe",
    supports_parse_showincludes = False,
    target_libc = "msvcrt",
    target_system_name = "x86_64-pc-windows-msvc",
    tool_paths = {{
        "ar": "bin/llvm-lib",
        "cpp": "bin/clang-cl",
        "gcc": "bin/clang-cl",
        "gcov": "bin/msvc-nop",
        "ld": "bin/lld-link",
        "ml": "bin/ml64.exe",
        "nm": "bin/msvc-nop",
        "objcopy": "bin/msvc-nop",
        "objdump": "bin/msvc-nop",
        "strip": "bin/msvc-nop",
    }},
    toolchain_identifier = "clang_cl_xwin_x64",
)

cc_toolchain_config(
    name = "clang_cl_xwin_arm64_config",
    abi_libc_version = "local",
    abi_version = "local",
    archiver_flags = ["/MACHINE:ARM64"],
    compiler = "clang-cl",
    cpu = "arm64_windows",
    dbg_mode_debug_flag = "/DEBUG",
    default_link_flags = ["/MACHINE:ARM64"],
    fastbuild_mode_debug_flag = "/DEBUG",
    host_system_name = "local",
    msvc_cl_path = "bin/clang-cl-arm64",
    msvc_env_include = "{env_include}",
    msvc_env_lib = "{env_lib_arm64}",
    msvc_env_path = "/usr/bin:/bin",
    msvc_env_tmp = "/tmp",
    msvc_lib_path = "bin/llvm-lib-arm64",
    msvc_link_path = "bin/lld-link-arm64",
    msvc_ml_path = "bin/clang-cl-arm64",
    supports_parse_showincludes = False,
    target_libc = "msvcrt",
    target_system_name = "aarch64-pc-windows-msvc",
    tool_paths = {{
        "ar": "bin/llvm-lib-arm64",
        "cpp": "bin/clang-cl-arm64",
        "gcc": "bin/clang-cl-arm64",
        "gcov": "bin/msvc-nop-arm64",
        "ld": "bin/lld-link-arm64",
        "ml": "bin/clang-cl-arm64",
        "nm": "bin/msvc-nop-arm64",
        "objcopy": "bin/msvc-nop-arm64",
        "objdump": "bin/msvc-nop-arm64",
        "strip": "bin/msvc-nop-arm64",
    }},
    toolchain_identifier = "clang_cl_xwin_arm64",
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = ":all_files",
    ar_files = ":all_files",
    as_files = ":all_files",
    compiler_files = ":all_files",
    dwp_files = ":empty",
    linker_files = ":all_files",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 1,
    toolchain_config = ":clang_cl_xwin_config",
    toolchain_identifier = "clang_cl_xwin_x64",
)

cc_toolchain(
    name = "cc_toolchain_arm64",
    all_files = ":all_files_arm64",
    ar_files = ":all_files_arm64",
    as_files = ":all_files_arm64",
    compiler_files = ":all_files_arm64",
    dwp_files = ":empty",
    linker_files = ":all_files_arm64",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 1,
    toolchain_config = ":clang_cl_xwin_arm64_config",
    toolchain_identifier = "clang_cl_xwin_arm64",
)
"""

def _msvc_cc_impl(rctx):
    llvm = rctx.attr.llvm_repo.repo_name
    xwin = rctx.attr.xwin_repo.repo_name
    splat = "external/{}/splat".format(xwin)

    rctx.file(
        "bin/clang-cl",
        _CLANG_CL_WRAPPER.format(
            arch = "x86_64",
            llvm = llvm,
            target = "x86_64-pc-windows-msvc",
            target_flags = "-msse4.1 -msse4.2",
            xwin = xwin,
        ),
        executable = True,
    )
    rctx.file(
        "bin/clang-cl-arm64",
        _CLANG_CL_WRAPPER.format(
            arch = "aarch64",
            llvm = llvm,
            target = "aarch64-pc-windows-msvc",
            target_flags = "",
            xwin = xwin,
        ),
        executable = True,
    )
    rctx.file(
        "bin/lld-link",
        _LLD_LINK_WRAPPER.format(
            arch = "x86_64",
            llvm = llvm,
            target = "x86_64-pc-windows-msvc",
            xwin = xwin,
        ),
        executable = True,
    )
    rctx.file(
        "bin/lld-link-arm64",
        _LLD_LINK_WRAPPER.format(
            arch = "aarch64",
            llvm = llvm,
            target = "aarch64-pc-windows-msvc",
            xwin = xwin,
        ),
        executable = True,
    )
    for tool in ("llvm-lib", "llvm-rc", "llvm-mt"):
        wrapper = _PASSTHROUGH_WRAPPER.format(llvm = llvm, tool = tool)
        rctx.file("bin/" + tool, wrapper, executable = True)
        rctx.file("bin/" + tool + "-arm64", wrapper, executable = True)
    rctx.file("bin/msvc-nop", _NOP_WRAPPER, executable = True)
    rctx.file("bin/msvc-nop-arm64", _NOP_WRAPPER, executable = True)
    # cc-rs resolves the x64 MASM assembler as `ml64.exe` from PATH on
    # non-windows hosts (blake3); ARM64 never receives this x64-only shim.
    for name in ("ml64.exe", "ml64"):
        rctx.file("bin/" + name, _ML64_WRAPPER.format(llvm = llvm), executable = True)

    # The MSVC feature/action-config machinery, verbatim from the resolved
    # rules_cc (same mechanism @local_config_cc uses on real Windows hosts).
    rctx.template("windows_cc_toolchain_config.bzl", rctx.attr._config_bzl, executable = False)

    rctx.file(
        "toolchain.cmake",
        _TOOLCHAIN_CMAKE.format(
            clang_cl = "clang-cl",
            lld_link = "lld-link",
            llvm_mt = "llvm-mt",
            llvm_rc = "llvm-rc",
            processor = "AMD64",
            target = "x86_64-pc-windows-msvc",
        ),
        executable = False,
    )
    rctx.file(
        "toolchain-arm64.cmake",
        _TOOLCHAIN_CMAKE.format(
            clang_cl = "clang-cl-arm64",
            lld_link = "lld-link-arm64",
            llvm_mt = "llvm-mt-arm64",
            llvm_rc = "llvm-rc-arm64",
            processor = "ARM64",
            target = "aarch64-pc-windows-msvc",
        ),
        executable = False,
    )

    # INCLUDE/LIB for raw cc_* actions. Includes are architecture-independent;
    # libraries are selected independently for each target toolchain.
    env_include = ";".join([
        splat + "/crt/include",
        splat + "/sdk/include/ucrt",
        splat + "/sdk/include/um",
        splat + "/sdk/include/shared",
        splat + "/sdk/include/winrt",
        splat + "/sdk/include/cppwinrt",
    ])
    env_lib_x64 = ";".join([
        splat + "/crt/lib/x86_64",
        splat + "/sdk/lib/um/x86_64",
        splat + "/sdk/lib/ucrt/x86_64",
    ])
    env_lib_arm64 = ";".join([
        splat + "/crt/lib/aarch64",
        splat + "/sdk/lib/um/aarch64",
        splat + "/sdk/lib/ucrt/aarch64",
    ])
    rctx.file(
        "BUILD.bazel",
        _BUILD.format(
            env_include = env_include,
            env_lib_arm64 = env_lib_arm64,
            env_lib_x64 = env_lib_x64,
        ),
        executable = False,
    )

msvc_cc_repository = repository_rule(
    implementation = _msvc_cc_impl,
    doc = "Target-specific clang-cl/lld-link cc toolchains for x86_64 and aarch64 Windows MSVC.",
    attrs = {
        "llvm_repo": attr.label(
            default = "@llvm_msvc_tools//:BUILD.bazel",
            doc = "Anchor into the pruned LLVM tools repo (canonical name source; not fetched here).",
        ),
        "xwin_repo": attr.label(
            default = "@xwin_sysroot//:BUILD.bazel",
            doc = "Anchor into the xwin CRT/SDK sysroot repo (canonical name source; not fetched here).",
        ),
        "_config_bzl": attr.label(
            default = "@rules_cc//cc/private/toolchain:windows_cc_toolchain_config.bzl",
            doc = "rules_cc's Windows cc_toolchain_config implementation, copied into this repo.",
        ),
    },
)
