// Auto-generated by scripts/generate-embedded-translations.ts
// Do not edit manually.

import type { TranslationFile } from "./index";
import en_json from "./lang/en.json" with { type: "json" };
import en_commands_json from "./lang/en-commands.json" with { type: "json" };
import en_hotkeys_json from "./lang/en-hotkeys.json" with { type: "json" };
import en_runtime_json from "./lang/en-runtime.json" with { type: "json" };
import en_settings_appearance_json from "./lang/en-settings-appearance.json" with { type: "json" };
import en_settings_context_json from "./lang/en-settings-context.json" with { type: "json" };
import en_settings_files_json from "./lang/en-settings-files.json" with { type: "json" };
import en_settings_full_json from "./lang/en-settings-full.json" with { type: "json" };
import en_settings_interaction_json from "./lang/en-settings-interaction.json" with { type: "json" };
import en_settings_memory_json from "./lang/en-settings-memory.json" with { type: "json" };
import en_settings_model_json from "./lang/en-settings-model.json" with { type: "json" };
import en_settings_providers_json from "./lang/en-settings-providers.json" with { type: "json" };
import en_settings_shell_json from "./lang/en-settings-shell.json" with { type: "json" };
import en_settings_tasks_json from "./lang/en-settings-tasks.json" with { type: "json" };
import en_settings_tools_json from "./lang/en-settings-tools.json" with { type: "json" };
import en_tips_json from "./lang/en-tips.json" with { type: "json" };
import en_ui_json from "./lang/en-ui.json" with { type: "json" };
import zh_json from "./lang/zh.json" with { type: "json" };
import zh_commands_json from "./lang/zh-commands.json" with { type: "json" };
import zh_hotkeys_json from "./lang/zh-hotkeys.json" with { type: "json" };
import zh_runtime_json from "./lang/zh-runtime.json" with { type: "json" };
import zh_settings_appearance_json from "./lang/zh-settings-appearance.json" with { type: "json" };
import zh_settings_context_json from "./lang/zh-settings-context.json" with { type: "json" };
import zh_settings_files_json from "./lang/zh-settings-files.json" with { type: "json" };
import zh_settings_full_json from "./lang/zh-settings-full.json" with { type: "json" };
import zh_settings_interaction_json from "./lang/zh-settings-interaction.json" with { type: "json" };
import zh_settings_memory_json from "./lang/zh-settings-memory.json" with { type: "json" };
import zh_settings_model_json from "./lang/zh-settings-model.json" with { type: "json" };
import zh_settings_providers_json from "./lang/zh-settings-providers.json" with { type: "json" };
import zh_settings_shell_json from "./lang/zh-settings-shell.json" with { type: "json" };
import zh_settings_tasks_json from "./lang/zh-settings-tasks.json" with { type: "json" };
import zh_settings_tools_json from "./lang/zh-settings-tools.json" with { type: "json" };
import zh_tips_json from "./lang/zh-tips.json" with { type: "json" };
import zh_ui_json from "./lang/zh-ui.json" with { type: "json" };

export const EMBEDDED_TRANSLATIONS: Record<string, TranslationFile> = {
	"en-commands": en_commands_json as TranslationFile,
	"en-hotkeys": en_hotkeys_json as TranslationFile,
	"en-runtime": en_runtime_json as TranslationFile,
	"en-settings-appearance": en_settings_appearance_json as TranslationFile,
	"en-settings-context": en_settings_context_json as TranslationFile,
	"en-settings-files": en_settings_files_json as TranslationFile,
	"en-settings-full": en_settings_full_json as TranslationFile,
	"en-settings-interaction": en_settings_interaction_json as TranslationFile,
	"en-settings-memory": en_settings_memory_json as TranslationFile,
	"en-settings-model": en_settings_model_json as TranslationFile,
	"en-settings-providers": en_settings_providers_json as TranslationFile,
	"en-settings-shell": en_settings_shell_json as TranslationFile,
	"en-settings-tasks": en_settings_tasks_json as TranslationFile,
	"en-settings-tools": en_settings_tools_json as TranslationFile,
	"en-tips": en_tips_json as TranslationFile,
	"en-ui": en_ui_json as TranslationFile,
	en: en_json as TranslationFile,
	"zh-commands": zh_commands_json as TranslationFile,
	"zh-hotkeys": zh_hotkeys_json as TranslationFile,
	"zh-runtime": zh_runtime_json as TranslationFile,
	"zh-settings-appearance": zh_settings_appearance_json as TranslationFile,
	"zh-settings-context": zh_settings_context_json as TranslationFile,
	"zh-settings-files": zh_settings_files_json as TranslationFile,
	"zh-settings-full": zh_settings_full_json as TranslationFile,
	"zh-settings-interaction": zh_settings_interaction_json as TranslationFile,
	"zh-settings-memory": zh_settings_memory_json as TranslationFile,
	"zh-settings-model": zh_settings_model_json as TranslationFile,
	"zh-settings-providers": zh_settings_providers_json as TranslationFile,
	"zh-settings-shell": zh_settings_shell_json as TranslationFile,
	"zh-settings-tasks": zh_settings_tasks_json as TranslationFile,
	"zh-settings-tools": zh_settings_tools_json as TranslationFile,
	"zh-tips": zh_tips_json as TranslationFile,
	"zh-ui": zh_ui_json as TranslationFile,
	zh: zh_json as TranslationFile,
};
