import * as fs from "node:fs/promises";
import * as crypto from "node:crypto";
import * as path from "node:path";

const reset = process.argv.includes("--reset");
const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");
const archivePrefix = "embedded-addons.";
const archiveSuffix = ".tar.gz";

const embeddedAddonTypedefs = `/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string} sha256
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 * @property {string} sha256
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {number} napiAbi
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */`;

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;
if (reset) {
	await Bun.write(outputPath, stubContent);
	try {
		const entries = await fs.readdir(nativeDir);
		await Promise.all(
			entries
				.filter(entry => entry.startsWith(archivePrefix) && entry.endsWith(archiveSuffix))
				.map(entry => fs.unlink(path.join(nativeDir, entry))),
		);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
	process.exit(0);
}

interface CandidateAddon {
	variant: "modern" | "baseline" | "default";
	filename: string;
}

interface AvailableAddon extends CandidateAddon {
	size: number;
	sha256: string;
	content: Uint8Array;
}

const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
const targetArch = Bun.env.TARGET_ARCH || process.arch;
const platformTag = `${targetPlatform}-${targetArch}`;
const candidates: CandidateAddon[] =
	targetArch === "x64"
		? [
				{ variant: "modern", filename: `pi_natives.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `pi_natives.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `pi_natives.${platformTag}.node` }];

const available: AvailableAddon[] = [];
for (const candidate of candidates) {
	const addonPath = path.join(nativeDir, candidate.filename);
	const file = Bun.file(addonPath);
	if (!(await file.exists())) continue;
	const content = await file.bytes();
	available.push({
		...candidate,
		size: content.byteLength,
		content,
		sha256: crypto.createHash("sha256").update(content).digest("hex"),
	});
}

if (available.length === 0) {
	const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
	throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
}
const packageJson = (await Bun.file(packageJsonPath).json()) as {
	version: string;
	ompNative: { napiAbi: number; platformTags: string[] };
};
if (!packageJson.ompNative.platformTags.includes(platformTag)) {
	throw new Error(`Unsupported native embed target ${platformTag}`);
}

const archiveFilename = `${archivePrefix}${platformTag}${archiveSuffix}`;
const archivePath = path.join(nativeDir, archiveFilename);
const archiveEntries: Record<string, Uint8Array> = {};
for (const addon of available) {
	archiveEntries[addon.filename] = addon.content;
}
const archiveBytes = await new Bun.Archive(archiveEntries, { compress: "gzip", level: 9 }).bytes();
await Bun.write(archivePath, archiveBytes);
const archiveSha256 = crypto.createHash("sha256").update(archiveBytes).digest("hex");

const files = available
	.map(
		addon =>
			`\t\t{ variant: ${JSON.stringify(addon.variant)}, filename: ${JSON.stringify(addon.filename)}, size: ${addon.size}, sha256: ${JSON.stringify(addon.sha256)} },`,
	)
	.join("\n");

const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

import archivePath from ${JSON.stringify(`../native/${archiveFilename}`)} with { type: "file" };

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(platformTag)},
\tnapiAbi: ${packageJson.ompNative.napiAbi},
\tversion: ${JSON.stringify(packageJson.version)},
\tarchive: {
\t\tformat: "tar.gz",
\t\tfilename: ${JSON.stringify(archiveFilename)},
\t\tfilePath: archivePath,
\t\tsha256: ${JSON.stringify(archiveSha256)},
\t},
\tfiles: [
${files}
\t],
};
`;

await Bun.write(outputPath, content);
